apiVersion: v1
kind: Service
metadata:
  name: management-ui
  labels:
    app: management-ui
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: management-ui
#  type: NodePort
    type: ClusterIP


