apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: launcher.gcr.io/google/mongodb4
        name: mongodb
        args:
        # toutes IP autorisées
        - --bind_ip_all
        # storage document-level. cf https://docs.mongodb.com/manual/core/wiredtiger/
        - --storageEngine wiredTiger
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: data
            mountPath: /data/db
            subPath: data
        resources:
          requests:
            cpu: 50m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 512Mi     
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-volumeclaim
