apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: launcher.gcr.io/google/mongodb3
        name: mongodb
        volumeMounts:
          - name: data
            mountPath: /data/db
            subPath: data
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 200m
          memory: 200Mi 
#        env:
# sans ces variables, la securité est desactivée
#        - name: MONGO_INITDB_ROOT_USERNAME
#          value: mongoadm
#        - name: MONGO_INITDB_ROOT_PASSWORD
#          value: mongoadm123       
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-volumeclaim
