apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
      spec:
#        type: NodePort
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true