apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: management-api
  labels:
    app: management-api
spec:
  selector:
    matchLabels:
      app: management-api
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: management-api
    spec:
      containers:
      - name: management-api
        image: graviteeio/management-api:latest
        ports:
        - containerPort: 8083
        env:
        - name: GRAVITEE_DS_MONGODB_HOST
          value: mongodb
        - name: GRAVITEE_DS_MONGODB_PORT
          value: "27017"
        - name: GRAVITEE_DS_ELASTIC_HOST
          value: "elastic:sx6zgx7k9z49sf9hkfxkzwz8@elasticsearch-es-http"
        - name: GRAVITEE_DS_ELASTIC_PORT
          value: "9200"
