apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: management-api
  labels:
    app: management-api
spec:
  selector:
    matchLabels:
      app: management-api
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: management-api
    spec:
      containers:
      - name: management-api
        image: graviteeio/management-api:latest
        ports:
        - containerPort: 8083
        env:
        - name: gravitee_management_mongodb_uri
          value: mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
        - name: gravitee_analytics_elasticsearch_endpoints_0
          value: http://elasticsearch:9200
