apiVersion: v1
kind: Service
metadata:
  name: management-api
  labels:
    app: management-api
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  selector:
    app: management-api
  type: NodePort


