apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: graviteeio/gateway:latest
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8082
        livenessProbe:
          httpGet:
            path: /
            port: 8082
        env:
        - name: GRAVITEE_DS_MONGODB_HOST
          value: mongodb
        - name: GRAVITEE_DS_MONGODB_PORT
          value: "27017"
        - name: GRAVITEE_DS_ELASTIC_HOST
          value: elasticsearch-es-http
        - name: GRAVITEE_DS_ELASTIC_PORT
          value: "9200"
        - name: GIO_MIN_MEM
          value: 128m
        - name: GIO_MAX_MEM
          value: 256m
