apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: graviteeio/gateway:latest
        ports:
        - containerPort: 8082
        env:
        - name: gravitee_management_mongodb_uri
          value: mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
        - name: gravitee_ratelimit_mongodb_uri
          value: mongodb://mongodb:27017/gravitee?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000&socketTimeoutMS=5000
        - name: gravitee_reporters_elasticsearch_endpoints_0
          value: http://elasticsearch:9200
