apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: graviteeio/gateway:${GATEWAY_VERSION}
        ports:
        - containerPort: 8082
        env:
        - name: GRAVITEEIO_MONGODB_HOST
          value: ${MONGODB_HOST}
        - name: GRAVITEEIO_MONGODB_PORT
          value: ${MONGODB_PORT}
        - name: GRAVITEEIO_ELASTIC_HOST
          value: ${ELASTIC_HOST}
        - name: GRAVITEEIO_ELASTIC_PORT
          value: ${ELASTIC_PORT}
