apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1 
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: graviteeio/gateway:latest
        ports:
        - containerPort: 8082
        env:
        - name: GRAVITEEIO_MONGODB_HOST
          value: mongodb
        - name: GRAVITEEIO_MONGODB_PORT
          value: "27017"
        - name: GRAVITEEIO_ELASTIC_HOST
          value: elasticsearch
        - name: GRAVITEEIO_ELASTIC_PORT
          value: "9200"
