kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch-volumeclaim
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi